### PR TITLE
no sleep after a task; add verify_chain_of_trust integration tests

### PR DESCRIPTION
**Pull request by escapewindow**
This is kind of 2 PRs in one.

- removed the unnecessary `await asyncio.sleep(1)` after a task. I don't think we need it. This should give us a little more throughput on our scriptworker pools.

- added `verify_chain_of_trust` against production tasks in our integration tests. This uses taskcluster indexes to find the latest production tasks to verify, and then runs chain of trust verification against them. This should help catch any bustage before we merge, though running `verify_cot` manually is still encouraged.

We don't have indexes for pushapk / beetmover / balrog, so we find these through the latest decision task. We're not able to run cot verification against them if their deps haven't successfully completed, so sometimes we'll skip these. I don't have a great solution here, other than possibly adding indexes for these tasks in the future.

### CODE REVIEW

**Comment by escapewindow** [comment]
@JohanLorenzo let me know if you want me to ramp up another scriptworker reviewer :)

**Comment by MihaiTabara** [comment]
Would love to ramp-up in scriptworker, if there's room at the table.

**Comment by JohanLorenzo** [comment]
This PR looks good for somebody else to get started. I can give a second, if you'd like

**Comment by escapewindow** [comment]
@mihaitabara if you want to give this review a spin, go for it and feel free to ask questions :)

**Comment by MihaiTabara** [comment]
Absolutely, thank you both! Am hoping to get this done before Aki's PTO. Otherwise, by Monday for sure. If it needs to be completed before that, please feel free to 302 to @JohanLorenzo.

**Comment by escapewindow** [comment]
Rebased against master.

**Comment by MihaiTabara** [comment]
Please keep'em coming, I'm starting to like these :) Sorry for initial delays, I'll act with more prompt action next time! Feel free to ping @JohanLorenzo as well for a second check just to make sure I didn't miss anything.

**Comment by escapewindow** [comment]
Thanks!

**Pull request merged**
