### PR TITLE
Fix verify_cot command line script by making sure to instantiate the …

### PR DESCRIPTION
**Pull request by Callek**
…Taskcluster Queue.

### CODE REVIEW

**Comment by escapewindow** [comment]
I wasn't sure if this was intermittent bustage or code bustage. I:

1. reran one of your travis runs. It stayed red.
2. pushed master to my fork. It went green. https://travis-ci.org/escapewindow/scriptworker/builds/425837994
3. pushed this PR branch to my fork. It went red. https://travis-ci.org/escapewindow/scriptworker/builds/425840935

That's not definitive, but does suggest that this change breaks things.

I'm not seeing the verify_cot bustage you're speaking of, but I can try it from the docker image to see if I can replicate.

**Comment by Callek** [comment]
@escapewindow I think the errors are just me not adjust tests (+ mocking) (I'll look into that momentarily..)

The error I hit is:
```
root@bfdbf391289b:/data# verify_cot --task-type decision --cot-product firefox Nz3UpqlgRd6TnW-tqmDhZA
INFO:scriptworker:Artifacts are in /tmp/tmp2rlyx70b
Traceback (most recent call last):
  File "/usr/local/bin/verify_cot", line 11, in <module>
    load_entry_point('scriptworker', 'console_scripts', 'verify_cot')()
  File "/data/scriptworker/cot/verify.py", line 1870, in verify_cot_cmdln
    context.task = event_loop.run_until_complete(context.queue.task(opts.task_id))
AttributeError: 'NoneType' object has no attribute 'task'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fed22034438>
```

**Comment by escapewindow** [comment]
I'm able to run verify_cot without patching on my docker image based off master.

**Comment by Callek** [comment]
...discussed on IRC this boils down to the credentials not being defined, and thus the queue wasn't instantiated (since that only happens on credentials set)

**Comment by escapewindow** [comment]
Looks like I didn't notice this happening because I had a `~/.scriptworker` file with creds =\

**Comment by escapewindow** [comment]
This should be fixed now, as of https://github.com/mozilla-releng/scriptworker/pull/320 . Thank you!

**Pull request closed without merging**
