### PR TITLE
remove old cot keys

### LINKED ISSUE #509: unit tests busted on new pip dependency resolver
https://github.com/pypa/pip/issues/9168
https://discuss.python.org/t/announcement-pip-20-3-release/5948
https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020

### PR DESCRIPTION
**Pull request by escapewindow**
~The prod tests will show us when the latest release/nightly graphs are all based on tasks using the new keys; let's not merge until these are green, or we explicitly determine that we don't need to wait on a given bustage.~

Green! I had to adjust our test configs to get this green due to #509, but this now fixes #509 as well.

### CODE REVIEW

**Comment by escapewindow** [comment]
> FAILED tests/test_production.py::test_verify_production_cot[mozilla-release win64 en-US repackage signing]
> FAILED tests/test_production.py::test_verify_production_cot[android-components release]

These probably need new releases to go green. m-r goes to build on Monday; I don't know when the next A-C release is.

> FAILED tests/test_production.py::test_verify_production_cot[fenix beta]
This appears to be an index that points to an expired task. We may want to update this test.

Also, we might want to add xpi-manifest indexes to these tests.

**Comment by escapewindow** [comment]
Down to 

>FAILED tests/test_production.py::test_verify_production_cot[mozilla-release win64 en-US repackage signing]
FAILED tests/test_production.py::test_verify_production_cot[android-components release]
FAILED tests/test_production.py::test_verify_production_cot[xpi-manifest cpmanager]

All of these failed on build:docker-image. I'll need to rebuild cached tasks in each of these, and potentially others (scriptworker{,-scripts}, glean, ?).

**Comment by escapewindow** [comment]
- Rebuilt xpi-manifest docker images
- Rebuilt android-components cached tasks
- Rebuilt scriptworker-scripts docker images
- Glean actions aren't working properly. Opened a [PR](https://github.com/mozilla/glean/pull/1734) to try to fix so I can rebuild the `build-docker-image-linux` task.

**Comment by escapewindow** [comment]
Tests are busted due to #509

**Review by bhearsum — APPROVED** [review]

**Pull request merged**
