### PR TITLE
Enhance error message when creds are missing

### PR DESCRIPTION
**Pull request by JohanLorenzo**
If you don't specify credentials (either because you forgot, or because you didn't paste things correctly in `secrets.json`), you end up with: `scriptworker.yaml credentials: type <class 'NoneType'> is not <class 'frozendict.frozendict'>!`

This patch replaces with that one instead:
```
scriptworker.yaml credentials needs to be defined!
```

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Time for me to add a new test

**Comment by JohanLorenzo** [comment]
I might have found a small bug while writing the test, but I'd like to check that with you @escapewindow . If a key is not present in `config`, `check_config` doesn't append an error message. From the code of `create_config`, I believe this should not happen by design. Do I get that correctly?

**Comment by escapewindow** [comment]
That's correct.  The quick fix is probably something like

```python
missing_keys = set(DEFAULT_CONFIG.keys()) - set(config.keys())
if missing_keys:
    messages.append("Missing config keys {}!".format(missing_keys))
```

Want me to add or do you want to?

**Comment by JohanLorenzo** [comment]
I know what test to add. I can add this along this patch

**Pull request merged**
