### PR TITLE
Make scriptworker retry more whenever CoT fails to connect to Github

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Fixes https://github.com/mozilla-releng/scriptworker/issues/419. What do you think @escapewindow?

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
The CI bustage is going to be fixed in #421

**Comment by JohanLorenzo** [comment]
Makes sense. I wasn't sure of the `retry_sync` approach because the library already retries requests for us. So we may end up hammering github with 5 * 5 requests in a single task run. That sounds quite big to me. What do you think @escapewindow? I'm fine changing this patch to `retry_sync` it.

**Comment by escapewindow** [comment]
Setting the task to intermittent-task means we may retry immediately in the next task run, so we may get 5*5 attempts, with minimal sleep time in between. With a `retry_sync`, we have the ability to change the sleep time logic for a longer sleep time (30s? `n` minutes?), since we already tried 5x in the GitHub object.

Having said that, I'm not 100% sure if this will be an issue, so I'm ok with holding off on `retry_sync` til we know we need it.

**Comment by JohanLorenzo** [comment]
You're right, using `retry_sync` would give a better control on the waiting. I gave it a shot. Please let me know what you think of it 🙂 @escapewindow

**Pull request merged**
