### PR TITLE
Bug 1868558 - Distrust old CoT keys

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Depends on https://github.com/mozilla-releng/scriptworker/pull/629

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Removing review because we haven't rotated every single repo. I'm on it.

**Comment by hneiva** [comment]
Looks like this is ready for landing? All checks are now passing

**Comment by JohanLorenzo** [comment]
Ah, nice! I was expecting this to turn green today. I'll get this merged today and deploy it tomorrow, then. I communicated to Release SRE that we will invalidate the keys tomorrow.

**Review by ahal — APPROVED** [review]
\o/

**Pull request merged**
