### PR TITLE
Use Github Checks for taskcluster reporting

### PR DESCRIPTION
**Pull request by bhearsum**

### CODE REVIEW

**Comment by escapewindow** [comment]
Timeout bustage appears to be #509 ; merging master in or rebasing the PR should resolve.

**Comment by bhearsum** [comment]
https://phabricator.services.mozilla.com/D123440 for the necessary ci-config change for this

**Review by escapewindow — COMMENTED** [review]
Looks good, and I like that the `checks` tab is populated now.
The ci-config patch appears to be merged.

Do you know why we're getting this?
Screen Shot 2021-08-24 at 9 28 17 AM

Setting change needed? Are we missing a decision task name here?

**Comment by bhearsum** [comment]
> Looks good, and I like that the `checks` tab is populated now.
> The ci-config patch appears to be merged.
> 
> Do you know why we're getting this?
> Screen Shot 2021-08-24 at 9 28 17 AM
> 
> Setting change needed? Are we missing a decision task name here?

That's due to branch protection settings:
image

If we want to depend on a single required check, we'll need to add a diamond closing one (eg: pr-complete). Alternatively, we can add all of the tasks as required checks (or not worry about it at all).

**Comment by escapewindow** [comment]
It looks like in #512 we had that. I'm guessing moving to checks-v1 removes that?
Screen Shot 2021-08-24 at 12 47 00 PM

**Comment by escapewindow** [comment]
I think the real answer here is "we should port the scriptworker repo to taskgraph". =\

**Comment by bhearsum** [comment]
> It looks like in #512 we had that. I'm guessing moving to checks-v1 removes that?
> Screen Shot 2021-08-24 at 12 47 00 PM

Yeah, checks replaces the overall "this task group passed or failed" with per-task status'. We can punt on this for now if you want, it's not a big deal.

**Comment by escapewindow** [comment]
Taskgraph is #534.

**Pull request merged**
