### PR TITLE
drop py36; add py39

### LINKED ISSUE #494: drop support for py3.6, add support for py3.9
#493 fixed mypy but broke py36 tests. Aiui we're running on at least py37, sometimes py38.

Let's drop support for py36, and add support for py39, since we may want to upgrade some scriptworkers to py39 at some point.

### PR DESCRIPTION
**Pull request by escapewindow**
Fixes #494

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]

**Comment by escapewindow** [comment]
Thanks!

**Comment by escapewindow** [comment]
Doh, did I merge a broken PR?

**Comment by escapewindow** [comment]
No, pytest-asyncio released 0.15.0 between the time the tests ran here, and when I merged the PR. I suspect this may have broken our tests.

**Comment by escapewindow** [comment]
https://github.com/pytest-dev/pytest-asyncio/issues/209

**Pull request merged**
