### PR TITLE
Updated integration_credentials to credentials in README

### PR DESCRIPTION
**Pull request by BrandonTang**
Noticed this problem while getting started with scriptworker.

### CODE REVIEW

**Comment by escapewindow** [comment]
The integration credentials are specifically needed for running integration tests through tox. This section is for tox testing, so I believe this is correct; are you hitting errors running tox?

If you're not referring to tox, it's in `scriptworker.yaml.tmpl` [here](https://github.com/mozilla-releng/scriptworker/blob/master/scriptworker.yaml.tmpl#L23-L26). The readme might need clarification about that, though.

**Comment by escapewindow** [comment]
We likely want to point people at [ReadTheDocs](http://scriptworker.readthedocs.io/en/latest/index.html) for anything more in depth, and specifically [Adding new scriptworker instances of an existing type](http://scriptworker.readthedocs.io/en/latest/new_instance.html) ([source](https://github.com/mozilla-releng/scriptworker/blob/master/docs/new_instance_types.md)).  That page can probably use some improvement :)

**Comment by escapewindow** [comment]
@BrandonTang do you have thoughts here? I'm leaning towards closing this PR, but I'm happy to make doc clarifications if the above isn't clear.

**Comment by BrandonTang** [comment]
You can go ahead and close the PR, I realize now that the integration credentials are specifically for running integration tests through tox. What you stated is clear enough so I don't believe doc clarifications are necessary, thanks!

**Pull request closed without merging**
